### ISSUE TITLE
Discussion Notes 10/03/14

### ISSUE THREAD

**Issue by thermokarst** [codeforanchorage/trailstranscoder#1]
Mike (@mkbrk) & Matt (@thermokarst) met for a few hours on 10/03/14 to discuss the trails data and related activities. Following are a few notes saved for posterity.

![image](https://cloud.githubusercontent.com/assets/274668/4512440/6d093984-4b40-11e4-9d0e-dd2eeaefede9.png)

```
trailstranscoder
├── finished_data [final output]
├── misc [for playing with transient ideas]
│   ├── script
│   └── thoughts
├── scripts [the main execution scripts]
├── source-data [upstream data]
│   ├── dnr
│   └── muni
├── sql [if we pull in postgis, any relevant scripts]
│   └── create_scripts
└── working_data [intermediate directory]
```

**Comment by mkbrk** [comment]
I was looking some more at ogr2ogr. The SQL dialect it supports seems pretty powerful. That, in combination with the geo-clipping options, would go a long way toward transcoding/normalizing the trail data. Here's an idea for how we could structure a config file to orchestrate the transforms:

```
{
   "source": "trails_shp",
   "destination": "kincaid.geojson",
   "sql": "select 'Muni' as Source, SYSTEM_NAM as System, TRAIL_NAME as Name, 'Muni/' + SYSTEM_NAM + '/' + TRAIL_NAME as Identifier, SURFACE as Surface,TRAIL_CLAS as Class,LIGHTING as Lighting,GRADE as Difficulty,SKI_TYPE as SkiType from trails",
   "clip": {"southwest":[123,456], "northeast":[456,567]}
}
```

That would get turned into the appropriate ogr2ogr command and executed as part of the workflow. The result of running all these is a pile of right-sized geojson with normalized, predictable field names.

**Comment by thermokarst** [comment]
@mkbrk: Check out the update I just pushed, does that fall in line with what you were thinking?

**Comment by mkbrk** [comment]
@thermokarst I like it a lot! Since the config is valid Python we have all kinds of interesting options. Feels like a winner to me...

**Comment by mkbrk** [comment]
@thermokarst Minor nuance I just thought of. What if the config py files exported a list instead of an object? This would allow us to group similar configs, which might be more intuitive, but also would allow us to do some fancy things like base one config on another. For example (my Python is not good, so grain of salt...):

```
kincaid_all = {
    "crs": "crs:84",
    "source": "../source-data/trails_shp",
    "destination": "../temp-data/kincaid-bounding-box.geojson",
    "sql": '''
        SELECT 'Muni' AS Source,
            SYSTEM_NAM AS System,
            TRAIL_NAME AS Name,
            'Muni/' + SYSTEM_NAM + '/' + TRAIL_NAME AS Identifier,
            SURFACE AS Surface,
            TRAIL_CLAS AS Class,
            LIGHTING AS Lighting,
            GRADE AS Difficulty,
            SKI_TYPE AS SkiType
        FROM trails
        ''',
    "clip": {
        "southwest": ["-150.1153", "61.12301"],
        "northeast": ["-149.98707", "61.18463"]
    }
}

kincaid_ski = {
    "crs": kincaid["crs"],
    "source": kincaid["source"],
    "destination": "../temp-data/kincaid-xc.geojson",
    "sql": kincaid["sql"] +  " WHERE SYSTEM_NAM = 'Kincaid Ski Trails'",
    "clip": kincaid["clip"]
}

config = (kincaid,kincaid_ski)
```

**Comment by thermokarst** [comment]
@mkbrk: 0aeffc2 demonstrates a potential scheme for subconfigs.

**Comment by mkbrk** [comment]
@thermokarst I think that will get us started at least. Hard to know exactly what options we're going to want until we get in there. I'll fill in a few more scenarios for Kincaid and see if I hit any walls.

**Comment by thermokarst** [comment]
Archiving.
