### ISSUE TITLE
KMZ vs KML files for DNR data

### ISSUE THREAD

**Issue by mkbrk** [codeforanchorage/trailstranscoder#3]
Background: the KMZ file format appears to be a ZIP-like wrapper around KML, which is just plain old XML. 

In my initial experimenting with the ogr2ogr command-line tool, it didn't like reading KMZ, but was fine with KML. So, I used Google Earth to open the KMZ and then export the KML file from within it. 

@thermokarst It looks like your latest iteration of the processing engine uses KMZ instead of KML for the DNR data. When I run it, I get the same error as before ("unable to open the datasource..."). Long story short, I'm wondering if we might have different version of GDAL running, one of which favors KMZ and one of which doesn't. 

**ogr2ogr --version** gives me 1.11, though I see that there's a 1.11.1 available now.

**Comment by thermokarst** [comment]
From the dev env:
`GDAL 1.10.1, released 2013/08/26`

@mkbrk: Are you running ogr2ogr on your host machine?

I think it is important to utilize the upstream sources in a manner that requires no modification on our end, so manually extracting KML from the KMZ seems like a bit of a hurdle that could/should be avoided.

**Comment by thermokarst** [comment]
I see two options at the moment that make sense (not necessarily exclusive from each other):
- enforce a gdal version when running main.py
- utilize pythons [zipfile module](https://docs.python.org/2/library/zipfile.html) to extract the KML at runtime.

**Comment by mkbrk** [comment]
@thermokarst Yes, I'm running it on the host, with GDAL installed via homebrew.

I agree that we want to work with KMZ vs KML. I'm guessing it has to do with the version of libkml I have. I'll poke around a bit more.

**Comment by thermokarst** [comment]
Have you run `ogrinfo --formats`? When I run that on my homebrew version, I have no LIBKML loaded. There are two KML-related drivers, straight KML, and LIBKML --- LIBKML is responsible for KMZ files, from what I can tell. 

Looks like you have to specifically include LIBKML when building from homebrew (--with-libkml):

```
gdal: stable 1.11.1 (bottled), HEAD
http://www.gdal.org/
/usr/local/Cellar/gdal/1.11.0 (228 files, 33M)
  Poured from bottle
/usr/local/Cellar/gdal/1.11.1 (229 files, 34M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gdal.rb
==> Dependencies
Required: libpng ✔, jpeg ✔, giflib ✔, libtiff ✔, libgeotiff ✔, proj ✔, geos ✔, sqlite ✔, freexl ✔, libspatialite ✔
Optional: postgresql ✔, mysql ✘
==> Options
--complete
    Use additional Homebrew libraries to provide more drivers.
--enable-armadillo
    Build with Armadillo accelerated TPS transforms.
--enable-mdb
    Build with Access MDB driver (requires Java 1.6+ JDK/JRE, from Apple or Oracle).
--enable-opencl
    Build with OpenCL acceleration.
--enable-unsupported
    Allow configure to drag in any library it can find. Invoke this at your own risk.
--with-libkml
    Build with Google's libkml driver (requires libkml --HEAD or >= 1.3)
--with-mysql
    Build with mysql support
--with-postgresql
    Build with postgresql support
--with-python
    Build with python support
--HEAD
    install HEAD version
```

**Comment by mkbrk** [comment]
@thermokarst Yup, that's got to be the issue! Installing complete GDAL now.

**Comment by thermokarst** [comment]
I can confirm, building GDAL with the `--with-libkml` flag solves the KMZ problem for me when running on my mac.

**Comment by mkbrk** [comment]
For the record, installed with --complete and it did _not_ work (libkml apparently not included). Installing with --with-libkml now.

Update: that worked. 

Summary: 
- I was attempting to run the python scripts in my host (OSX) as opposed to in the dev environment.
- I had prepped the host by installing GDAL from homebrew with default options
- While this mostly worked, it failed on KMZ input files
- Uninstalling/re-installing GDAL from homebrew with the --with-libkml flag did the trick
